--***********************************************
--  MODULO 03                   
--***********************************************


--***********************************************
--  CASO DESARROLLADO 1                    
--***********************************************

IF OBJECT_ID('PROYECTOS_INDUSTRIALES') IS NULL 
    DROP DATABASE PROYECTOS_INDUSTRIALES


CREATE DATABASE PROYECTOS_INDUSTRIALES

USE PROYECTOS_INDUSTRIALES

CREATE TABLE DISTRITO(
    COD_DIS CHAR(3) NOT NULL PRIMARY KEY,
    NOM_DIS VARCHAR(40)
)

CREATE TABLE CLIENTE(
    IDE_CLI CHAR(5) NOT NULL PRIMARY KEY,
    NOMBR_CLI VARCHAR(50),
    RUC_CLI CHAR(11) UNIQUE,
    COD_DIS CHAR(3),
    EMA_CLI VARCHAR(35) DEFAULT 'No cuenta',
    FOREIGN KEY(COD_DIS) REFERENCES DISTRITO
)

CREATE TABLE PROYECTO(
    NUM_PRO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FEC_PRO DATE,
    MON_PRO MONEY
)

CREATE TABLE ENCARGADO(
    IDE_ENC CHAR(5) NOT NULL PRIMARY KEY ,
    APE_ENC VARCHAR(30) NOT NULL,
    NOM_ENC VARCHAR(30) NOT NULL,
    CAR_ENC VARCHAR(30) NOT NULL, 
    COD_DIS CHAR(3) NOT NULL REFERENCES DISTRITO,
    FIN_ENC DATE NOT NULL
)

CREATE TABLE DETALLE_PROYECTO(
    NUM_PRO INT NOT NULL,
    IDE_CLI CHAR(5) NOT NULL,
    IDE_ENC CHAR(5) REFERENCES ENCARGADO,
    DES_DET VARCHAR(40),
    PRIMARY KEY(NUM_PRO, IDE_CLI)
)

ALTER TABLE PROYECTO
    ADD CONSTRAINT CHK_MONTO
    CHECK (MON_PRO>0)

ALTER TABLE ENCARGADO
    ADD CONSTRAINT CHK_CARRERA
    CHECK (CAR_ENC IN('Jefe','Contador','Supervisor','Vendedor'))

ALTER TABLE DETALLE_PROYECTO
    ALTER COLUMN DES_DET VARCHAR(100)

ALTER TABLE CLIENTE
    ADD TEL_CLI CHAR(11) NOT NULL,
    HIJ_CLI INT NOT NULL

ALTER TABLE CLIENTE
    DROP COLUMN HIJ_CLI

INSERT INTO DISTRITO VALUES ('ABC','SAN JUAN')

UPDATE CLIENTE
    SET EMA_CLI = 'maria_lopez@gMail.com'
    WHERE NOMBR_CLI = 'María Lopez'

UPDATE CLIENTE
    SET TEL_CLI = '00000000'

UPDATE PROYECTO
    SET MON_PRO -= 5000
    WHERE YEAR(FEC_PRO) = 2012 AND MONTH(FEC_PRO) BETWEEN 1 AND 6


--***********************************************
-- CASO DESARROLLADO 2           
--***********************************************

IF OBJECT_ID('RENT_CAR') IS NOT NULL
    DROP DATABASE RENT_CAR


CREATE DATABASE RENT_CAR

USE RENT_CAR

CREATE TABLE DISTRITO(
    IDE_DIS CHAR(3) NOT NULL PRIMARY KEY,
    DES_DIS VARCHAR(40) NOT NULL
)

CREATE TABLE CLIENTE(
    IDE_CLI CHAR(5) NOT NULL PRIMARY KEY,
    APE_CLI VARCHAR(30) NOT NULL,
    NOM_CLI VARCHAR(30) NOT NULL,
    DNI_CLI CHAR(8) NOT NULL,
    TEL_CLI VARCHAR(25) NOT NULL DEFAULT '000-00000',
    IDE_DIS CHAR(3),
    FOREIGN KEY(IDE_DIS) REFERENCES DISTRITO
)

CREATE TABLE ALQUILER(
    NUM_ALQ INT NOT NULL PRIMARY KEY,
    FEC_ALQ DATE NOT NULL,
    MON_ALQ MONEY NOT NULL CHECK (MON_ALQ > 0)
)

CREATE TABLE AUTOMOVIL(
    MAT_AUT CHAR(10) NOT NULL PRIMARY KEY,
    COL_AUT VARCHAR(30) NOT NULL CHECK (COL_AUT IN ('Rojo','Plata','Negro')),
    MOD_AUT VARCHAR(30) NOT NULL
)

CREATE TABLE DETALLE_ALQUILLER(
    NUM_ALQ INT NOT NULL,
    IDE_CLI CHAR(5) NOT NULL,
    MAT_AUT CHAR(10) NOT NULL,
    FOREIGN KEY(NUM_ALQ) REFERENCES ALQUILER,
    FOREIGN KEY(IDE_CLI) REFERENCES CLIENTE,
    FOREIGN KEY(MAT_AUT) REFERENCES AUTOMOVIL
)

ALTER TABLE CLIENTE
    ADD COR_CLI VARCHAR(30) NOT NULL

INSERT INTO AUTOMOVIL VALUES ('123','Rojo','DFSD')